[package]
name = "sandbox"
version = "0.1.0"
authors = ["virchau13 <virchau13@mail.hexular.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seccomp-sys = "0.1.3"
libc = "0.2"
nix = "0.18.0"
rlimit = "0.4.0"
